name: crisalid-directory-bridge CI

on:
  pull_request:
    branches: [ "dev-main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libldap2-dev libsasl2-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set AIRFLOW_HOME
        run: echo "AIRFLOW_HOME=$(mktemp -d)" >> $GITHUB_ENV

      - name: Create symbolic link for dags
        run: |
          mkdir -p "${AIRFLOW_HOME}/dags"
          ln -s "${GITHUB_WORKSPACE}" "${AIRFLOW_HOME}/dags"

      - name: Initialize Airflow configuration
        run: |
          airflow config list --defaults > "${AIRFLOW_HOME}/airflow.cfg"
          echo "load_examples = False" >> "${AIRFLOW_HOME}/airflow.cfg"

      - name: Test with pytest
        run: |
          APP_ENV=TEST pytest

  lint:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libldap2-dev libsasl2-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with Pylint
        run: |
          pylint --rcfile=.pylintrc  ./tasks *.py
